# @package _global_

# dataset config
data:
  train_files: /data/dlf/code/self-questioning-lm/selfplay_data/ch_painting/train.parquet
  val_files: /data/dlf/code/self-questioning-lm/selfplay_data/ch_painting/test.parquet

  max_prompt_length: 512
  max_response_length: 1024
  truncation: left

trainer:
  balance_batch: false
  self_play: true
  proposer_parser_version: v1

actor_rollout_ref:
  rollout:
    n: 4
  model:
    path: /data/share/hub/models/Qwen/Qwen2.5-VL-3B-Instruct

