# @package _global_

actor_rollout_ref:
  actor:
    ppo_mini_batch_size: 4
    ppo_micro_batch_size_per_gpu: 1
  rollout:
    log_prob_micro_batch_size_per_gpu: 1
  ref:
    log_prob_micro_batch_size_per_gpu: 1    

data:
  train_batch_size: 4